paths:
  key: 'keys/key.pem'
  cert: 'keys/cert.pem'

model:
  name: 'Dolphin'
  base_url: 'http://localhost:11434'
  temperature: 0
  num_predict: 1536

urls:
  ai: 'https://localhost:8000/ai'
  db: 'https://localhost:5000'

n_threads: 3